### ISSUE TITLE
How about standardizing the way config initializers are called?

### ISSUE THREAD

**Issue by ceki** [virtualdogbert/logback-groovy-config#1]
Wouldn't it be better to allow configurators be loaded as Java services? 

See also https://jira.qos.ch/browse/LOGBACK-1655 which is related.

**Comment by virtualdogbert** [comment]
I don't really know what that means. I haven't changed your code all that much to get the compiler restrictions in place. However, pull requests are welcome, provided they are properly documented and have tests or a way to test the new code. 

I just moved into my new house last week, so I know I've been slacking on getting this released. I'm going to try to get an initial version into maven central this weekend.

**Comment by ceki** [comment]
The idea is for logback-groovy-config to contain a [service provider](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) implementing the  [Configurator interface](https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/spi/Configurator.java) interface , so that logback-classic delegates to it automatically at start up time.

You would also need to declare your implementation under the META-INF/services/ch.qos.logback.classic.spi.Configurator pointing to your implementation. 

Please note that the Configurator interface will change in logback 1.3.0-beta1. (The return type of the configure() method will change.)

**Comment by virtualdogbert** [comment]
@ceki Finally had some time to look at this, but I can't seem to be able to get the service to pick up in my sample app:

https://github.com/virtualdogbert/logback-test-g5

Any ideas on what I could be missing?

**Comment by virtualdogbert** [comment]
@ceki I used this example to figure out a couple of missing pieces:
https://github.com/ozkanpakdil/spring-examples/blob/master/logback-code-config/src/main/java/com/mascix/demo/MyLogbackConfigurer.java

but it still doesn't completely work. It will now call my configurator kicking off the DSL initialization, but for some reason, that is not the same as running the init manually from BootStraps.groovy. At this point, it looks like it should work but it still isn't. I did a little more debugging and it seems like my init is getting overridden before I get to BootStrap.groovy, but I don't know by what. I'm using the same test app updated:
https://github.com/virtualdogbert/logback-test-g5

**Comment by ceki** [comment]
Have you declared your configurator under `META-INF/services/ch.qos.logback.classic.spi.Configurator`  ? Here is an [example](https://github.com/ozkanpakdil/spring-examples/tree/master/logback-code-config/src/main/resources/META-INF/services).

**Comment by virtualdogbert** [comment]
@ceki yes that was the part I figured out based on the example:
https://github.com/ozkanpakdil/spring-examples/blob/master/logback-code-config/src/main/java/com/mascix/demo/MyLogbackConfigurer.java

and in a debugger, I can see that my GroovyConfigurator gets called and if I inspect the context afterward I can see that it has my changes. However by the time I get to the BootStrap.groovy, if I check the context again it seems like my changes are gone. I'm thinking there may be something in Grails overriding my changes. I also asked about this on the Grails slack channel, but I don't expect a response till at least tomorrow.

**Comment by ceki** [comment]
Have you tried invoking the your `GroovyConfigurator`  on a temporary `ch.qos.logback.classic.LoggerContext` that you created? What happens then? 

Here is the type of code I have in mind:

```
   LoggerContext loggerContext = new LoggerContext();
   GroovyConfigurator configurator = new GroovyConfigurator();
   configurator.setContext(loggerContext);
   configurator.doConfigure( "/path/to/logback.groovy");
```

If the above code works, and you say that Logback is picking up `GroovyConfigurator`  as a configurator service, then it sounds like Grail is doing some secondary configuration after logback configures itself with `GroovyConfigurator` .

**Comment by virtualdogbert** [comment]
Yep, I tried that in the BootStrap.groovy(commented-out code) of my test app:
https://github.com/virtualdogbert/logback-test-g5

and it works just fine after that, so that is why I think Grails is doing something between the initialization of my configurator and BootStrap.groovy. We'll see If anyone responds to my question about that on Slack.

**Comment by ceki** [comment]
Looking at the 'gradle.properties' of the grails-core project, it looks like it is using logback version 1.2.7  which has built-in support for logback.groovy. Perhaps Grails has its own classloader and two distinct copies of logback live in distinct class loaders.

**Comment by virtualdogbert** [comment]
Don't know if that variable is actually being used but doing a dep report in Gradle shows that 1.2.10 is what is being used:
```
+--- org.springframework.boot:spring-boot-starter-logging -> 2.6.4
|    +--- ch.qos.logback:logback-classic:1.2.10
|    |    +--- ch.qos.logback:logback-core:1.2.10
|    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
```
And that is coming from the SpringBoot part of grails. Although I added links to my question and that thought to the context:
https://app.slack.com/client/T07LCCCSU/C07M0GTDE/thread/C07M0GTDE-1666630793.139399

**Comment by virtualdogbert** [comment]
Just to reference this here as well the issue was spring boot and its default config because it didn't know I had initialized the logging. 

There's a check for its initialization here:
https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L122

**Comment by virtualdogbert** [comment]
Just release version 1.0. Take a look at the docs before using.
