### ISSUE TITLE
Does Java 17 supported?

### ISSUE THREAD

**Issue by mpsoftesis** [virtualdogbert/logback-groovy-config#6]
hi there 

in process of upgrading my Spring Boot configuration to 3+ I've added `io.github.virtualdogbert:logback-groovy-config:1.14.1`

And catch 

```Exception in thread "main" BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 61```

Does java 17 supported or I miss something

**Comment by virtualdogbert** [comment]
Hmm, strange looks like there might be an issue with the Groovy version I'm using. 

Currently, I'm compiling with Java 8 and Groovy 3.0.13. I'll have to take a look.

You might also run into an issue that that version because I don't know if Spring Boot has released with logback at 1.4. Last I checked they were still on 1.2.x, but have updated the code for a future release.

**Comment by mpsoftesis** [comment]
@virtualdogbert tnx for you reply

I've found logback 1.4.6 in my classpath 

and Groovy 3.0.17

**Comment by virtualdogbert** [comment]
So I don't really keep up with Spring Boot that much but use it passively through Grails. So I went to https://start.spring.io/ to spin up a demo app. I set up to use Java 17(corretto). The first problem I ran into was it was defaulting To Groovy 4 and apparently, that is not compatible with the Logback DSL, which I inherited, and did not write myself. I just pulled the DSL from Logback's history, to create this project and added some security to the script. So in the future, I'm probably going to have to rewrite the Logback DSL, which will take some time.

I came back to this ticket and saw you were using Groovy 3.0.17, so I switched to that and I was able to get the application working. My build.gradle config looks like this:
```
plugins {
	id 'groovy'
	id 'org.springframework.boot' version '3.0.6'
	id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenLocal()
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	//implementation 'org.apache.groovy:groovy'
	implementation 'org.codehaus.groovy:groovy-all:3.0.17'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation "io.github.virtualdogbert:logback-groovy-config:1.14.1"
}

tasks.named('test') {
	useJUnitPlatform()
}
```

So I haven't been able to reproduce the exact issue that you have. Maybe you could provide a sample app that recreates the issue I could look more closely and see if I see something.

**Comment by mpsoftesis** [comment]
@virtualdogbert tnx fro your time 

I will have next "update window" in 3 weeks and will return to this question 

will close issue for now.

Once again - tnx a lot!
